### ISSUE TITLE
Install using Ruby 3.3 fails because usage of anonymous parameters forwarding inside blocks

### ISSUE THREAD

**Issue by lucianghinda** [PhlexUI/phlexui_issues#1]
**Describe the bug**
When I try to add PhlexUi to a Rails 7.1 application running Ruby 3.3 I get the error: 

```
<internal: rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require':
.gem/ruby/3.3.0/gems/phlex_ui-0.1.3/lib/phlex_ui/aspect_ratio.rb:17: anonymous block parameter is also used within block (SyntaxError)
```

**To Reproduce**

```bash
bundle add phlex_ui
bin/importmap pin phlex_ui
```

**Expected behavior**
There should not raise an error on Ruby 3.3

**Additional context**
In Ruby 3.3 anonymous parameters forwarding inside blocks are disallowed. 
See [this for reference](https://rubyreferences.github.io/rubychanges/3.3.html) and the discussion in [Ruby tracker](https://bugs.ruby-lang.org/issues/19370)

**Comment by kieranklaassen** [comment]
Yes, I just bought it but cannot use it.

**Comment by georgekettle** [comment]
Thanks for opening this issue @lucianghinda 🙏🏼 

I have updated all anonymous blocks to named blocks and have pushed latest release of gem for both `phlex_ui` and `phlex_ui_pro`

You can upgrade to `v0.1.5` to access the update for ruby 3.3.0

Please let me know if there is anything I have missed :)
