### ISSUE TITLE
TailwindCSS does not scan CSS classes of PhlexUI components

### ISSUE THREAD

**Issue by seniorihor** [PhlexUI/phlexui_issues#2]
**Describe the bug**
TailwindCSS does not include CSS classes that are used within the PhlexUI gem.

**To Reproduce**
1. I setup PhlexUI in Gemfile:
```
gem 'phlex-rails'
gem 'phlex_ui', '~> 0.1', git: 'https://github.com/PhlexUI/phlex_ui.git', branch: 'main'
gem 'tailwindcss-rails', '~> 2.1'
```
2. In view, I render any PhlexUI component:
```
render PhlexUI::Button.new { "Button" }
```
3. I compile CSS:
```
rails tailwindcss:build
```
4. In the browser, I see an "empty" HTML component with CSS classes added, but the CSS classes do not apply.

**Expected behavior**
CSS styles for used components applied.

**Screenshots**
![button](https://github.com/PhlexUI/phlexui_issues/assets/836117/f3676a81-52a5-4b8a-8245-71a378eb04c7)

**Desktop:**
 - OS: macos
 - Browser: Chrome
 - Version: 120.0.6099.129
 
 How should I configure it so TailwindCSS apply styles to the used PhlexUI components?

**Comment by seniorihor** [comment]
The workaround I found is to add this to `config/tailwind.config.js`:
```
module.exports = {
  content: [
   ...
    '/usr/local/bundle/bundler/gems/phlex_ui-*/lib/**/*.rb'
  ],
...
}
```

@georgekettle Is it a recommended approach or there's a better way?

**Comment by johnmcdowall** [comment]
@seniorihor The docs do cover the Tailwind modifications you'd need to make. Scroll to 'Install Styles' and you'll see what you need to change. 

https://phlexui.com/docs/installation/rails_bundler

**Comment by georgekettle** [comment]
Thanks @johnmcdowall for this 😄
